### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by moookino** [iganeshk/standardnotes-extensions#5]
Hi @iganeshk,
it's not an issue, but heads up
I've created docker image to host those extensions easier without need to build them, just spin up and ready to use
It's exposed on 8043 port

https://hub.docker.com/r/moookino/snext

**Comment by konradwalsh** [comment]
thank you

**Comment by Ryonez** [comment]
@moookino Can I ask for you nginx config with this?
Been trying to get this going for over an over with no luck.

**Comment by moookino** [comment]
@Ryonez Hey, i'm not using any nginx in that image, here is docker-compose example how i spin it up
i'm using https://github.com/piranha/gostatic instead of nginx
```
version: "3.6"

services:
  snext:
    image: moookino/snext:latest
    container_name: snext
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snext.entrypoints=http"
      - "traefik.http.routers.snext.rule=Host(`example.domain.ltd`)"
      - "traefik.http.middlewares.snext-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.snext.middlewares=snext-https-redirect"
      - "traefik.http.routers.snext-secure.entrypoints=https"
      - "traefik.http.routers.snext-secure.rule=Host(`example.domain.ltd`)"
      - "traefik.http.routers.snext-secure.tls=true"
      - "traefik.http.routers.snext-secure.tls.certresolver=http"
      - "traefik.http.routers.snext-secure.service=snext"
      - "traefik.http.services.snext.loadbalancer.server.port=8043"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```
